[build]
publish = "public"
command = "hugo --gc --minify -b $GE_ORG_ES_URL"

[context.production.environment]
HUGO_VERSION = "0.152.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.staging]
command = "hugo --gc --minify --buildFuture -b $GE_ORG_ES_URL -e staging"

[context.staging.environment]
HUGO_VERSION = "0.152.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $GE_ORG_ES_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.152.2"

